389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
  
Example 2:
Input: s = "", t = "y"
Output: "y"
  
Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
class Solution {
public:
     //Solution: 1
    char findTheDifference(string s, string t) {
        char r=0;
        for(int i=0;i<s.size();i++)
        {
            r^=s[i]^t[i];
        }
        r^=t[t.size()-1];
        return r;
    }
 //Solution: 2   
        // char findTheDifference(string s, string t) {
        // char r=0,r1=0;
        // for(int i=0;i<s.size();i++)
        // {
        //     r+=s[i];
        //     r1+=t[i];
        // }
        // return (r1+t[t.size()-1])-r;
        
    // }
};
